# Generated by Django 3.2.4 on 2021-07-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'ordering': ('pk',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestcaseType',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('type', models.CharField(choices=[('AC', 'AC Station'), ('DC', 'DC Station'), ('CMN', 'Common')], default='CMN', max_length=20)),
                ('status', models.CharField(choices=[('n', 'none'), ('p', 'pass'), ('i', 'inconclusion'), ('f', 'fail'), ('e', 'error')], default='n', max_length=20)),
                ('build_status', models.CharField(choices=[('NA', 'Not available'), ('OK', 'Builded')], default='NA', max_length=20)),
                ('condition', models.TextField(blank=True)),
                ('expected', models.TextField(blank=True)),
                ('pics', models.TextField(blank=True)),
                ('pixit', models.TextField(blank=True)),
                ('path', models.TextField(blank=True)),
                ('msg_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testcase.messagetype')),
            ],
            options={
                'ordering': ('pk',),
                'abstract': False,
            },
        ),
    ]
